[package]
name = "getter_proc_macro_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["getter_macro"]

[dependencies]
getter_macro = {path = "getter_macro", version = "0.1.0"}
